asterisk:
   sipconfig: /home/admin2/tmp/sip-asterisk-control.conf
   sipcongigremote: /home/admin2/asterisk/sip-centers.conf
   configheader: ;This is a SIP config header 
   siptemplate: sip-burgs
   sshport: 22
   known_hosts: /home/admin2/workspaces/mibs/mibs-asterisk-control/known_hosts
   ami_port: 5038 
spring:
    mvc:
          favicon:
             enabled : true
    main: 
          banner-mode: "off"
    thymeleaf: 
          cache: false
    redis:
          host : localhost
          port : 6379
    datasource:
        url: jdbc:mysql://172.16.30.148:3306/asterisk_control?useUnicode=yes&characterEncoding=UTF-8
        username: asterisk-admin
        password: Qrtp80%tvbMkt
    jpa:
        show-sql: false 
        database-platform: org.hibernate.dialect.MySQL5Dialect
        hibernate: 
              ddl-auto: update
logging:
    file: /var/log/mibs-asterisk-control.log    
server:      
    connection-timeout: -1 
    address: 172.16.30.49
    port: 8011
    servlet:
         context-path: /asterisk-control
    error:
       whitelabel:
          enabled: false         
          
          
         
  
