package mibs.asterisk.control;

import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;

/*
 * This Java source file was generated by the Gradle 'init' task.
 * git fetch --all
git reset --hard origin/{{your branch name}}
 */
@SpringBootApplication
public class App {
    public String getGreeting() {
        return "Hello world.";
    }

    public static void main(String[] args) {
    	System.out.println("Run me...");
        SpringApplication.run(App.class, args);
        
       
    }
}
