
spring:
    mvc:
          favicon:
             enabled : true
    main: 
          banner-mode: "off"
    thymeleaf: 
          cache: false
    redis:
          host : localhost
          port : 6379
    datasource:
        url: jdbc:mysql://127.0.0.1:3306/asterisk_control?useUnicode=yes&characterEncoding=UTF-8
        username: asterisk-admin
        password: 456852

    jpa:
        show-sql: false 
        database-platform: org.hibernate.dialect.MySQL5Dialect
        hibernate: 
              ddl-auto: update

logging:
    file: /var/log/mibs-asterisk-control.log    

server:      
    connection-timeout: -1 
    address: 127.0.0.1
    port: 8011
    servlet:
         context-path: /asterisk-control
    error:
       whitelabel:
          enabled: false         
          
          
         
  
